manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: urob
      revision: fix-mod-morph
      import: app/west.yml
  self:
    path: config
